name: SonarCloud Analysis - Frontend
# Workflow name displayed in GitHub Actions.

on:
  push:
    branches:
      - master
      - ScanCode
  pull_request:
# Triggers the workflow on each push to the "master" or "ScanCode" branches

jobs:
  sonarcloud:
    name: SonarCloud Frontend
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        # Clone the repository so that the files are available in the VM

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
        # Install Node.js version 18 to be able to run npm

      - name: Install dependencies
        run: npm install

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@v2
        with:
          projectBaseDir: .
          args: >
            -Dsonar.projectKey=svtozq_ViteReact-Project
            -Dsonar.organization=svtozq
            -Dsonar.sources=src
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
